name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Build and deploy
      env:
        HOST: your_droplet_ip
        USER: your_username
      run: |
        echo "Deploying to $HOST"
        scp -r ./backend $USER@$HOST:/path/to/your/backend
        scp -r ./frontend $USER@$HOST:/path/to/your/frontend
        ssh $USER@$HOST << 'EOF'
          cd /path/to/your/backend
          npm install
          pm2 restart all || pm2 start server.js --name backend

          cd /path/to/your/frontend
          npm install
          npm run build
          sudo cp -r build/* /var/www/html/
          sudo systemctl restart nginx
        EOF

