name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Build and deploy
      env:
        HOST: ${{ secrets.DO_HOST }}
        USER: ${{ secrets.DO_USER }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PORT: ${{ secrets.PORT }}
      run: |
        echo "Deploying to $HOST"
        scp -r ./dist $USER@$HOST:/path/to/your/backend
        scp -r ./frontend/build $USER@$HOST:/var/www/html
        ssh $USER@$HOST << 'EOF'
          cd /path/to/your/backend
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "SECRET_KEY=$SECRET_KEY" >> .env
          echo "PORT=$PORT" >> .env
          npm install
          pm2 restart all || pm2 start index.mjs --name backend
          sudo systemctl restart nginx
        EOF
