
name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.YOGA }}

    - name: Build and deploy
      env:
        HOST: ${{ secrets.DO_HOST }}
        USER: ${{ secrets.DO_USER }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        SENDER_EMAIL_ACCOUNT: ${{ secrets.SENDER_EMAIL_ACCOUNT }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: |
        echo "Deploying to $HOST"
        scp -r ./* $USER@$HOST:/
        scp -r ./dist $USER@$HOST:/var/www/html
        ssh $USER@$HOST << 'EOF'
          cd /
          echo "MONGODB_URI=$MONGODB_URI" >> .env
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
          echo "SENDER_EMAIL_ACCOUNT=$SENDER_EMAIL_ACCOUNT" >> .env
          echo "APP_PASSWORD=$APP_PASSWORD" >> .env
          pm2 restart all || pm2 start index.mjs --name backend
          sudo systemctl restart nginx
        EOF
